import 'package:get/get.dart';

class PetsController extends GetxController{

  List<Map<String, dynamic>> categoryList = [
    {
      'id': 1,
      'title': 'Dog',
      'image': 'Assets/images/dog.jpg',
      'details': 'Adopt or buy different breeds of dogs.',
      'age': '2 months',
      'price': '\$200',
      'isAdopted': false, // Fixed typo
    },
    {
      'id': 2,
      'title': 'Cat',
      'image': 'Assets/images/cat.jpg',
      'details': 'Find various breeds of cats for adoption.',
      'age': '5 months',
      'price': '\$300',
      'isAdopted': false,
    },
    {
      'id': 3,
      'title': 'Bird',
      'image': 'Assets/images/bird.jpg',
      'details': 'Parrots, canaries, and exotic birds available.',
      'age': '6 months',
      'price': '\$50',
      'isAdopted': false,
    },
    {
      'id': 4,
      'title': 'Fish',
      'image': 'Assets/images/fish.jpg',
      'details': 'Aquarium fish and accessories.',
      'age': '3 months',
      'price': '\$5',
      'isAdopted': false,
    },
    {
      'id': 5,
      'title': 'Rabbit',
      'image': 'Assets/images/Rabbit.jpg',
      'details': 'Different rabbit breeds for sale.',
      'age': '2 months',
      'price': '\$50',
      'isAdopted': false,
    },
    {
      'id': 6,
      'title': 'Hamster',
      'image': 'Assets/images/Hamster.jpg',
      'details': 'Tiny and adorable hamsters for your home.',
      'age': '1 month',
      'price': '\$10',
      'isAdopted': false,
    },
    {
      'id': 7,
      'title': 'Reptile',
      'image': 'Assets/images/reptile.jpg',
      'details': 'Turtles, lizards, and snakes.',
      'age': '1 year',
      'price': '\$50',
      'isAdopted': false,
    },
    {
      'id': 8,
      'title': 'Horse',
      'image': 'Assets/images/horse.jpg',
      'details': 'Horses and ponies available for purchase.',
      'age': '1 year',
      'price': '\$1000',
      'isAdopted': false,
    },
    {
      'id': 9,
      'title': 'Turtle',
      'image': 'Assets/images/turtle.jpg',
      'details': 'Find aquatic and land turtles.',
      'age': '1 year',
      'price': '\$30',
      'isAdopted': false,
    },
    {
      'id': 10,
      'title': 'Parrot',
      'image': 'Assets/images/parrot.jpg',
      'details': 'Talking and colorful parrots available.',
      'age': '6 months',
      'price': '\$100',
      'isAdopted': false,
    },
    {
      'id': 11,
      'title': 'Snake',
      'image': 'Assets/images/snake.jpg',
      'details': 'Non-venomous pet snakes for reptile lovers.',
      'age': '6 months',
      'price': '\$50',
      'isAdopted': false,
    },
    {
      'id': 12,
      'title': 'Guinea Pig',
      'image': 'Assets/images/Pigs.jpg',
      'details': 'Cute and friendly guinea pigs for adoption.',
      'age': '1 month',
      'price': '\$20',
      'isAdopted': false,
    },
    {
      'id': 13,
      'title': 'Ferret',
      'image': 'Assets/images/spider.jpg',
      'details': 'Playful and intelligent ferrets available.',
      'age': '1 year',
      'price': '\$100',
      'isAdopted': false,
    },
    {
      'id': 14,
      'title': 'Chinchilla',
      'image': 'Assets/images/Chinchillas.jpg',
      'details': 'Soft and fluffy chinchillas for sale.',
      'age': '6 months',
      'price': '\$100',
      'isAdopted': false,
    },
    {
      'id': 15,
      'title': 'Tarantula',
      'image': 'Assets/images/Tarantulas.jpg',
      'details': 'Exotic pet tarantulas available.',
      'age': '1 year',
      'price': '\$30',
      'isAdopted': false,
    },
    {
      'id': 16,
      'title': 'Frog',
      'image': 'Assets/images/frog.jpg',
      'details': 'Tree frogs, dart frogs, and more.',
      'age': '6 months',
      'price': '\$10',
      'isAdopted': false,
    },
    {
      'id': 17,
      'title': 'Goat',
      'image': 'Assets/images/goat.jpg',
      'details': 'Friendly and healthy goats for farm or pet.',
      'age': '1 year',
      'price': '\$100',
      'isAdopted': false,
    },
    {
      'id': 18,
      'title': 'Chicken',
      'image': 'Assets/images/chiken.jpg',
      'details': 'Backyard chickens and egg-laying breeds.',
      'age': '2 months',
      'price': '\$10',
      'isAdopted': false,
    },
    {
      'id': 19,
      'title': 'Duck',
      'image': 'Assets/images/ducks.jpg',
      'details': 'Various breeds of ducks for sale.',
      'age': '3 months',
      'price': '\$20',
      'isAdopted': false,
    },
    {
      'id': 20,
      'title': 'Pig',
      'image': 'Assets/images/Pigs.jpg',
      'details': 'Mini pigs and farm pigs available.',
      'age': '1 year',
      'price': '\$200',
      'isAdopted': false,
    },
  ].obs;
  // Function to update adoption status
  void adoptPet(int id) {
    int index = categoryList.indexWhere((pet) => pet['id'] == id);
    if (index != -1) {
      categoryList[index]['isAdopted'] = true;
      update(); // Notify GetX to update UI
    }
  }

}